server:
  port: 8002

spring:
  application:
    name: "service-consumer-demo"
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/